language: go

sudo: false

go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - tip

branches:
    only:
        - master
        - /^v\d+\.\d+\.\d+(-\S*)?$/

matrix:
    allow_failures:
        - go: tip

script: go test
